### ISSUE TITLE
Files on OneDrive are not tracked

### ISSUE THREAD

**Issue by florianbussmann** [wakatime/wakatime-cli#489]
When working with files stored on OneDrive they won't send a heartbeat ony my system.

`~/.wakatime.log` says file would not exist

> {"now": "2021/04/09 22:02:16 +0200", "version": "13.0.7", "plugin": "word/16.0 word-wakatime/2.1.0", "time": 1617998530.322588, "caller": "wakatime\\main.py", "lineno": 68, "is_write": true, "file": "https://d.docs.live.net/*****/Dokumente/*****.docx", "level": "DEBUG", "message": "File does not exist; ignoring this heartbeat."}

**Comment by alanhamlett** [comment]
Related to #623, which added support for `ssh://` and `sftp://` remote files.

**Comment by gandarez** [comment]
Which IDE @florianbussmann and @EtaoinWu are using to edit remote file on One Drive? And what were the steps you took to open them locally?

I've tried a spreadsheet on my personal One Drive account and when opened locally it's a HTML file with some embeded scripts and tags.

**Comment by florianbussmann** [comment]
@gandarez I used Microsoft Word with the wakatime Office Add-In (2.1.0) and there you can edit documents on OneDrive remotely

**Comment by EtaoinWu** [comment]
@gandarez Same here; WakaTime Office Add-ins. At the time of report I believe I was using 2.1.0. In Word (and other MS Office components) you can open an Onedrive remote file and edit it directly. So the easiest way to reproduce:

1. Have MS Word and WakaTime Office Add-ins installed.
2. Create an empty file, save it to your onedrive with arbitrary name. You might need to restart Word and reopen the file.
3. Do some edits to the file (it should trigger Word's autosave, or you can save manually) and WakaTime CLI should report that the "file does not exist".

**Comment by alanhamlett** [comment]
Is this fixed now that wakatime-cli supports reading files over http/https?

**Comment by EtaoinWu** [comment]
> Is this fixed now that wakatime-cli supports reading files over http/https?

I re-installed the plugin for Word, and the problem is still here. Apparently the word plugin still ships with `"version": "13.0.7"` of wakatime-cli, instead of `"version":"v1.49.0"` as my vscode plugin does.

**Comment by gandarez** [comment]
Office plugins are still using legacy python cli. It should be fixed soon.

**Comment by gandarez** [comment]
It should be fine as Office plugins are already using new wakatime-cli.
